## Q0: (0 point) 
- Please install Anaconda on your own PC or the PC in the lab. (Download link: https://www.anaconda.com/download/ )
- Please install related Python3 packages: numpy, scikit-learn, jupyter (pip3 install numpy, scikit-learn, jupyter)

## Q1: (100 point) 
Use NumPy module to define and operation the following operations on matrices and vectors. Please readme the following example and answer sub-questions 1-5 in jupyter notebook.

### Example for Q1
#### Question: 
- Calculate the matrix multiplication between random matrix A (shape 6x3) and random matrix B (shape 3x5)

In [92]:
import numpy as np
# 1. Generate random matrix A and B
rng = np.random.default_rng(12345) # random number generator

a = rng.random((6,3))
b = rng.random((3,5))

# 2. Execute matrix multiplication and assign the result to matrix C
c = np.matmul(a, b)
# 3. Print the shape and value of C
print(c.shape)
print(c)


(6, 5)
[[0.38729243 0.61171315 0.95849503 0.57728964 0.86146276]
 [0.70877114 0.45227887 0.65870666 0.38395736 0.59080964]
 [0.58765112 0.58414883 0.77618487 0.53650593 0.85466202]
 [0.89367681 0.84143152 1.09040748 0.7694417  1.23679366]
 [0.57481654 0.43690261 0.5103331  0.391045   0.65113282]
 [1.00498923 0.57637771 0.92034809 0.4729711  0.69605955]]


### (1) Define NumPy Array
#### Question: 
- Use NumPy to define the following matrix A and vector b, then print A and b
$$
 A = 
 \begin{bmatrix}
   1 & 7 & 3 & 3\\
   4 & 9 & 6 & 1\\
   2 & 8 & 5 & 4
  \end{bmatrix},
   b =
 \begin{bmatrix}
   7 \\
   4 \\
   1 \\
  \end{bmatrix}
$$


In [93]:
# Answer to sub-question 1
A = np.matrix([[1, 7, 3, 3], [4, 9, 6, 1], [2, 8, 5, 4]]) # build a matrix of 3 by 4
b = np.array([[7],[4],[1]])
print ("A is \n", A)
print("b is \n", b)


A is 
 [[1 7 3 3]
 [4 9 6 1]
 [2 8 5 4]]
b is 
 [[7]
 [4]
 [1]]


### (2) Basic Mathematical Operation
#### Question:  
- Mulitply a scalar 3 and substract a scalar 6 to each element in A, then print the new result matrix.

In [94]:
# Answer to sub-question 2
print("Origin A Matrix")
print(A)
# Multiply A by 3
# print(A)
# print(np.ones(A.shape, dtype=int))
# Substract 6 from each element of A 
result = A * 3 - np.ones(A.shape, dtype=int)*6

print("Result of manipulation with A")
print(result)


Origin A Matrix
[[1 7 3 3]
 [4 9 6 1]
 [2 8 5 4]]
Result of manipulation with A
[[-3 15  3  3]
 [ 6 21 12 -3]
 [ 0 18  9  6]]


### (3) Broadcast Mechanism
#### Question: 
- Use the broadcast mechanism in NumPy to add b to **each row** of the matrix A, then print the new result matrix.

In [95]:
# Answer to sub-question 3
# print(A.shape)
# print(b.shape)
new_matrix = A + b
print(new_matrix)


[[ 8 14 10 10]
 [ 8 13 10  5]
 [ 3  9  6  5]]


### (4) Dimension Manipulation Operation
#### Question: 
- (Slice) Get the first and the third column of the Matrix A to construct a new matrix, then print it.
- (Split) Split the Matrix A to three row vectors, then print them.

In [96]:
# Answer to sub-question 4
# print(A)
# print(A[0].shape)
A_row_1_and_3 = np.concatenate([A[0], A[2]])
print("Matrix built from first and thrid row of A")
print(A_row_1_and_3)
print()
for i in range(A.shape[0]):
    print("Vector ", i, sep="")
    temp_vector = A[i].reshape((A.shape[1],1))
    # print(temp_vector.shape)
    print(temp_vector)
    print()


Matrix built from first and thrid row of A
[[1 7 3 3]
 [2 8 5 4]]

Vector 0
[[1]
 [7]
 [3]
 [3]]

Vector 1
[[4]
 [9]
 [6]
 [1]]

Vector 2
[[2]
 [8]
 [5]
 [4]]



### (5) Matrix Operation
#### Question:
- Execute the SVD decompositon to the matrix A, then print the results (i.e. unitary matrix and singular value vector).

In [97]:
# Answer to sub-question 5
# print(A)
SVD_ans = np.linalg.svd(A)
U, S, Vh = SVD_ans
print("Unitary Matrix U is\n", SVD_ans[0])
# print(U.shape)
print("Vector(s) with the singular values are: \n", SVD_ans[1])
# print(S.shape)
print("Unitary Matrix Vh: \n", SVD_ans[2])
# print(Vh.shape)


Unitary Matrix U is
 [[-0.46553532 -0.4984117  -0.73134305]
 [-0.65418864  0.75034882 -0.09494137]
 [-0.59608228 -0.43423775  0.67536915]]
Vector(s) with the singular values are: 
 [17.33485114  3.09409544  0.96411065]
Unitary Matrix Vh: 
 [[-0.24658155 -0.80272413 -0.47892821 -0.25585012]
 [ 0.52826686 -0.06775631  0.27008511 -0.80212046]
 [ 0.24855007 -0.59217319  0.63599378  0.42786177]
 [ 0.77353379 -0.01933834 -0.54147365  0.32875186]]
